# Generated by Django 3.0.2 on 2020-02-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_auto_20200203_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='did_attend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managment.Event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='event_attendees',
        ),
    ]
