# Generated by Django 3.0.2 on 2020-02-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_auto_20200203_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
