# Generated by Django 3.0.2 on 2020-02-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_event_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.Attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.Event')),
            ],
        ),
    ]
