# Generated by Django 3.0.2 on 2020-02-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_auto_20200205_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
